CREATE TABLE [dbo].[Employees](
	[Id] [int] NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[MiddleName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[Nickname] [nvarchar](100) NULL,
	[Address1] [nvarchar](100) NOT NULL,
	[Address2] [nvarchar](100) NULL,
	[City] [nvarchar](100) NOT NULL,
	[State] [nvarchar](10) NOT NULL,
	[Zip] [nvarchar](20) NOT NULL,
	[HomePhone] [nvarchar](20) NULL,
	[CellPhone] [nvarchar](20) NULL,
	[Sex] [nvarchar](10) NOT NULL,
	[Ethnicity] [nvarchar](20) NULL,
	[Disabled] [nvarchar](10) NULL,
	[ProtectedVet] [nvarchar](20) NULL,
	[DisabledVet] [nvarchar](20) NULL,
	[Birthday] [date] NOT NULL,
	[Active] [bit] NOT NULL,
	[BusinessExt] [nvarchar](10) NULL,
	[EmployeeEmail] [nvarchar](100) NULL,
	[OriginalHireDate] [date] NOT NULL,
	[SeniorityDate] [date] NOT NULL,
	[TerminationDate] [date] NOT NULL,
	[TerminationCode] [nvarchar](20) NULL,
	[Rehired] [bit] NOT NULL ,
	[LicenseNumber] [nvarchar](20) NOT NULL ,
	[LicenseExp] [date] NOT NULL ,
	[CDL_NonCDL] [nvarchar](10) NOT NULL,
	[CDLMedExp] [date] NOT NULL,
	[CDLDriverType] [nvarchar](50) NOT NULL,
	[LicenseNotes] [ntext] NOT NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
))